meta_84/meta/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from .views import RegisterPage, CustomLoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from .views import upload

app_name = 'meta'

urlpatterns = [
    path('', TemplateView.as_view(template_name='meta/index.html'), name='index'),
    path('dashboard/', upload, name='dashboard'),
    path('about-us/', TemplateView.as_view(template_name='meta/about-us.html'), name='about-us'),
    path('faqs/', TemplateView.as_view(template_name='meta/faqs.html'), name='faqs'),
    path('contact-us/', TemplateView.as_view(template_name='meta/contact-us.html'), name='contact-us'),
    path('signup/', RegisterPage.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='meta:index'), name='logout'),

    # Change Password

    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='password/change-password.html',
            success_url='/'  # use this for home page
        ),
        name='change_password'
    ),

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password/password_reset_confirm.html',
             subject_template_name='password/password_reset_subject.txt',
             email_template_name='password/password_reset_email.html',
             success_url=reverse_lazy('meta:password_reset_done')
         ),
         name='password-reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password/password_reset_confirm.html',
             success_url=reverse_lazy('meta:password_reset_complete')
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
            template_name='password/password_reset_complete.html',
         ),
         name='password_reset_complete'),

]

meta_84/meta_84/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('meta.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meta_84/templates/password/change-password.html
{% extends "password/pass_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css  %} {% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
        {{ form|crispy }}
        <a href="{% url 'meta:index' %}">Back</a>
        <button type="submit">Submit</button>

  </form>


{% endblock %}

meta_84/templates/password/pass_base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    {% block css %} {% endblock %}
    <style media="screen">
      .asteriskField {
          display: none;
      }
    </style>

    <title>{% block title %} {% endblock %}</title>
  </head>
  <body>
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

meta_84/templates/password/password_reset.html
{% extends "password/pass_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css  %} {% endblock %}

{% block content %}
  <form method="post">
    {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" name="" value="Reset Password">

  </form>


{% endblock %}

meta_84/templates/password/password_reset_complete.html
{% extends "password/pass_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css  %} {% endblock %}

{% block content %}

<h2>Reset Password</h2>
<h3>Hurray! Your password has been changed.</h3>
<a href="{% url 'meta:login' %}">Click here to Login</a>

{% endblock %}

meta_84/templates/password/password_reset_confirm.html
{% extends "password/pass_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css  %} {% endblock %}

{% block content %}
<h2>Reset Password</h2>
<h3>Enter your new password</h3>
<form  method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form|crispy }}
<input type="submit" name="" value="Change Password">
</form>


{% endblock %}

meta_84/templates/password/password_reset_done.html
{% extends "password/pass_base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block css  %} {% endblock %}

{% block content %}
<h2>Reset Password</h2>
<p>We have sent you reset password link on your email. Please Check Your Email.</p>
<a href="{% url 'meta:index' %}">Back to Home Page</a>


{% endblock %}

meta_84/templates/password/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}Hey, You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'meta:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}