meta/core/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'core'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='home'),
    path('register/', views.RegisterPage.as_view(), name='register'),
    path('login/', views.CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='core:login'), name='logout'),
    path('core/', views.Core.as_view(), name='core'),
    path('dashboard/', TemplateView.as_view(template_name='dashboard.html'), name='dashboard'),

]

meta/meta/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

meta/core/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

meta/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100)
    last_name = forms.CharField(max_length=100)

    class Meta:
        model = User
        fields = ['first_name', 'last_name', "username", "email", "password1", "password2"]

meta/core/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import FormView
from django.contrib.auth.views import LoginView
from django.views.generic import View
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RegisterForm  # register
from django.contrib.auth import login
from django.urls import reverse_lazy

# Create your views here.


class RegisterPage(FormView):
    template_name = 'signup.html'
    form_class = RegisterForm  # django form
    success_url = reverse_lazy('core:core')

    def form_valid(self, form):
        user = form.save()
        if user is not None:  # if user is authenticated log in the user!
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    # we need to prevent authenticated user from registering!

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect('core:core')  # this is the page it will return instead of signing up
        return super(RegisterPage, self).get(*args, **kwargs)


class CustomLoginView(LoginView):
    template_name = 'login.html'
    fields = '__all__'
    redirect_authenticated_user = True  # if user is authenticated they should not be allowed to be in the login page

    def get_success_url(self):  # use this function whenever you need success url in login
        return reverse_lazy('core:core')


class Core(LoginRequiredMixin, View):  # must log in before viewing this page!
    login_url = '/login/'  # it will redirect here if the user is not logged in

    def get(self, request):
        context = {}
        return render(request, 'core.html', context)

class dashboard():
    dashboard_url = '/dashboard/'

    def get(self, request):
        context = {}
        return render(request, 'dashboard.html', context)
     

meta/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>{% block head %}Base {% endblock %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  {% block css %} {% endblock %}
</head>

<body>

    {% block content %}

    {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</body>

</html>

meta/templates/core.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  Dashboard

{% endblock %}

{% block css %} <link rel="stylesheet" href="{% static 'css/styles.css'%}">{% endblock %}

{% block content %}

<div class="head">
  <h1> Welcome {{ request.user }} </h1>
  <p>My name is {{ request.user.first_name }}</p>
  <p>Last logged in: {{ request.user.last_login}}</p>
  <p>Please upload your data</p>
  <a href="{% url 'core:logout' %}">Logout </a>


</div>


{% endblock %}

meta/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
  Home Page

{% endblock %}

{% block css %} <link rel="stylesheet" href="{% static 'css/styles.css'%}">{% endblock %}

{% block content %}

<div class="head">
  <h1> Welcome to our documentation please login or register to see more </h1>
  <a href="{% url 'core:login' %}">Login </a>
  <a href="{% url 'core:register' %}">Sign Up</a>


</div>


{% endblock %}

meta/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
  Login Page

{% endblock %}

{% block content %}
<h1>Login</h1>
  <form  action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" name="submit" value="Login in">

  </form>
  <p>Do not have an account? please sign up</p> <br>
  <a href="{% url 'core:register' %}">Sign Up</a>


{% endblock %}

meta/templates/signup.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
  SignUp Page

{% endblock %}

{% block content %}
<h1>Sign Up</h1>
  <form  action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" name="submit" value="Sign Up">

  </form>

<p> Have an account please sign in <a href="{% url 'core:login' %}">Sign in</a></p>

{% endblock %}