meta_84/meta/urls.py
from django.urls import path, reverse_lazy
from django.views.generic import TemplateView
from .views import RegisterPage, CustomLoginView
from django.contrib.auth.views import LogoutView
from django.contrib.auth import views as auth_views
from .views import upload

app_name = 'meta'

urlpatterns = [
    path('', TemplateView.as_view(template_name='meta/index.html'), name='index'),
    path('dashboard/', upload, name='dashboard'),
    path('about-us/', TemplateView.as_view(template_name='meta/about-us.html'), name='about-us'),
    path('faqs/', TemplateView.as_view(template_name='meta/faqs.html'), name='faqs'),
    path('contact-us/', TemplateView.as_view(template_name='meta/contact-us.html'), name='contact-us'),
    path('signup/', RegisterPage.as_view(), name='register'),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='meta:index'), name='logout'),

    # Change Password

    path(
        'change-password/',
        auth_views.PasswordChangeView.as_view(
            template_name='password/change-password.html',
            success_url='/'  # use this for home page
        ),
        name='change_password'
    ),

    # Forget Password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(
             template_name='password/password_reset_confirm.html',
             subject_template_name='password/password_reset_subject.txt',
             email_template_name='password/password_reset_email.html',
             success_url=reverse_lazy('meta:password_reset_done')
         ),
         name='password-reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='password/password_reset_confirm.html',
             success_url=reverse_lazy('meta:password_reset_complete')
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
            template_name='password/password_reset_complete.html',
         ),
         name='password_reset_complete'),

]

meta_84/meta_84/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('meta.urls')),
    path('admin/', admin.site.urls),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

meta_84/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <script src="https://kit.fontawesome.com/1f5aa4ec6b.js" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}"/>
    {% block title %} <title> Base </title> {% endblock %}
    {% block css %} <link rel="stylesheet" href="{% static 'css/static.css' %}"> {% endblock %}
    {% block js %} <script src="{% static 'js/static.js' %}" defer></script> {% endblock %}

</head>
<body>
<nav class="nav base-nav">
    <img src="{% static 'images/Logo.png' %}" alt="Logo">
    <div class="nav-links" title="links" id="navMenu">
        <a href="{% url 'meta:index'%}" class="nav-link" title="index">Home</a>
        <a href="{% url 'meta:about-us'%}" class="nav-link" title="about-us">About Us</a>
        <a href="{% url 'meta:faqs'%}" class="nav-link" title="faqs">FAQs</a>
        <a href="{% url 'meta:contact-us'%}" class="nav-link" title="contact-us">Contact Us</a>
    </div>
    <div class="nav-btns" id="navBtn">

        {% if user.is_authenticated %}
        <button type="submit" class="nav-btn"><a href="{% url 'meta:dashboard' %}" class="index-nav-sign-up">Dashboard</a></button>
        <button type="submit" class="nav-btn index-log"><a href="{% url 'meta:logout' %}" class="index-nav-log-in">Log Out</a></button>
        {% else %}
        <button type="submit" class="nav-btn"><a href="{% url 'meta:register' %}" class="index-nav-sign-up">Sign Up</a></button>
        <button type="submit" class="nav-btn index-log"><a href="{% url 'meta:login'%}" class="index-nav-log-in">Log In</a></button>
        {% endif %}


    </div>
    <div class="profile-circle">
        <i class="fa-solid fa-circle-user" id="profile"></i>
    </div>
    <div class="hamburger" id="hamburger">
        <div class="toggle-item"></div>
        <div class="toggle-item"></div>
        <div class="toggle-item"></div>
    </div>
</nav>

{% block content %} {% endblock content %}
<footer>
    <section class="footer-icons">
        <div>
            <p>Copyright of I4GXZURI project team 84 2022</p>
            <img src="{% static 'images/bi_c-circle.png' %}" alt="copyright">
        </div>
        <div>
            <img src="{% static 'images/ci_mail.png' %}" alt="">
            <img src="{% static 'images/twitter-vector.png' %}" alt="">
            <img src="{% static 'images/insta-vector.png' %}" alt="">
            <img src="{% static 'images/facebook-vector.png' %}" alt="">
        </div>
        <div>
            <p>Terms and Condition</p>
            <p>Privacy Policy</p>
        </div>
    </section>
</footer>
</body>
</html>

meta_84/templates/login.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="shortcut icon" href="{% static 'images/favicon.png' %}"/>
    <style media="screen">
    .asteriskField {
        display: none;
    }
    .fix {
      display: flex;
      padding-top: 2rem;
    }

    .fix-3 {
      margin-right: auto;
      margin-left: 1rem;
    }




    </style>
​
    <title>84Meta | Log In</title>

</head>
<body id="logInBody" class="log-in-body">
    <header class="log-in-header">
        <nav class="log-in-nav">
            <a href="{% url 'meta:index' %}" title="Back to Home"><img src="{% static 'images/Logo.png' %}" alt="logo"></a>
            <div class="log-in-sign-up">
                <p>
                    Are you a new user?
                </p>
                <button class="log-in-nav-btn">
                    <a href="{% url 'meta:register' %}" class="index-nav-sign-up">Sign Up</a>
                </button>
            </div>
        </nav>
    </header>
    <main class="log-in-main">
        <h2>Login Account</h2>
​
        <form  method="post" class="log-in-form">
          {% csrf_token %}
          <!-- Added this new rows -->
               {% if form.errors %}
               <div class="col-12 register-field">
                   <div class="alert alert-block alert-danger">
                       <ul>
                           <li> Incorrect Username or Password
                           </li>
                       </ul>
                   </div>
               </div>
               {% endif %}
          <div class="form-crispy">
                <div class="crispy-field">

                    {{ form.username|as_crispy_field }}
                </div>
                <div class="crispy-field">
                    {{ form.password|as_crispy_field }}
                </div>
                <div class="crispy-field log-in-forgot-rem fix">
                      <div class="fix-1">
                         {{ form.remember_me}}

                      </div>
                      <div class="fix-3">
                        Remember Me

                      </div>
                    <div class="fix-2">
                      <a href="" class="log-in-forgot">Forgot Password?</a>

                    </div>
                </div>
    ​       </div>
            <button type="submit" class="log-in-btn">Login</button>
            <div class="log-in-continue">
                <span class="log-in-line"></span>
                <p>Or continue with</p>
                <span class="log-in-line"></span>
            </div>
            <button type="submit" class="log-in-social log-in-google"><img src="{% static 'images/google-svgrepo-com (1) 1.png' %}" alt=""><a href="">Continue with Google</a></button>
            <button type="submit" class="log-in-social log-in-fb"><img src="{% static 'images/Facebook.png' %}" alt=""><a href="">Continue with Facebook</a></button>
​
      </form>
​
​
​
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
​
</body>
</html>

meta_84/templates/signup.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sign Up</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/sign.css' %}">
    <style media="screen">
    .asteriskField {
        display: none;
    }
    .fix-email, .fix-pass{
      margin-top: -1rem;
    }
    </style>
  </head>
  <body>
    <header class="sign-up-header">
        <nav class="sign-up-nav">
            <a href="{% url 'meta:index' %}" title="Back to Home"><img src="{% static 'images/Logo.png' %}" alt="logo"></a>
            <div class="sign-up-log-in">
                <p>
                    Already have an account?
                </p>
                <button class="sign-up-nav-btn">
                    <a href="{% url 'meta:login' %}" class="index-nav-sign-up">Log In</a>
                </button>
            </div>
        </nav>
    </header>
    <main class="sign-up-main">
        <h2>Create An Account</h2>
    <div class="form-crispy">
      <form class="sign-up-form" method="post" >
        {% csrf_token %}
          <div class="crispy-field">
              {{ form.first_name|as_crispy_field }}
          </div>
          <div class="crispy-field">
              {{ form.last_name|as_crispy_field }}
          </div>
          <div class="crispy-field">
            {{ form.username|as_crispy_field }}
​
          </div>
          <div class="crispy-field fix-email">
            {{ form.email|as_crispy_field }}
​
          </div>
          <div class="crispy-field fix-pass">
            {{ form.password1|as_crispy_field }}
​
          </div>
          <div class="crispy-field fix-pass">
            {{ form.password2|as_crispy_field }}
​
          </div>

          <!-- Added this new rows -->
               {% if form.errors %}
               <div class="col-12 register-field">
                   <div class="alert alert-block alert-danger">
                       <ul>
                           <li> Incorrect Field
                           </li>
                       </ul>
                   </div>
               </div>
               {% endif %}

​
          <button type="submit" name="" value="Sign Up" class="sign-up-btn">Sign Up</button>
          ​<p class="terms">By clicking  on sign up, you have agreed to all the <a>Terms and Conditions</a>.</p>


          <div class="sign-up-continue">
            <span class="sign-up-line"></span>
            <p>Or continue with</p>
            <span class="sign-up-line"></span>
            </div>
            <button type="submit" class="sign-up-social sign-up-google"><img src="{% static 'images/google-svgrepo-com (1) 1.png' %}" alt=""><a href="">Continue with Google</a></button>
            <button type="submit" class="sign-up-social sign-up-fb"><img src="{% static 'images/Facebook.png' %}" alt=""><a href="">Continue with Facebook</a></button>
​           </div>
      </form>
​
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>


    </main>
  </body>
</html>